---
- hosts: defaults
  sudo: yes
  vars:
    home_dir: /home/ubuntu
    emacs_dir: emacs
    dotfiles_dir: dotfiles
  tasks:

    - name: boot emacs first 
      command: emacs --daemon
      sudo: yes
      sudo_user: ubuntu
    - name: reboot emacs
      command: emacsclient -e '(progn (defun yes-or-no-p (p) t) (kill-emacs))' && emacs --daemon
      command: emacs --daemon
      sudo: yes
