---
- hosts: defaults
  sudo: yes
  vars:
    home_dir: /home/ubuntu
    emacs_dir: emacs
  tasks:
    - name: apt-get update
      command: apt-get update
    - name: apt-get install git
      apt: pkg=git
    - name: apt-get install tools
      apt: pkg=automake,make,g++,build-essential,autoconf,texinfo

    - name: get emacs from git repository
      git: repo=git://git.savannah.gnu.org/emacs.git
           dest=~/ update=no accept_hostkey=True
      
    - name: install emacs
      command: ./autogen.sh && ./configure && make && make install chdir={{home_dir}}/{{emacs_dir}}
