---
- hosts: defaults
  sudo: yes
  vars:
    home_dir: /home/ubuntu
    emacs_dir: emacs
    dotfiles_dir: dotfiles
  tasks:

    - name: install additinal tools for pdf-tools
      apt: pkg=libpng-dev,libz-dev,libpoppler-glib-dev,libpoppler-private-dev 

    - name: boot emacs first 
      command: emacs --daemon
    - name: reboot emacs
      command: emacsclient -e '(progn (defun yes-or-no-p (p) t) (kill-emacs))' && emacs --daemon
